# security-action.yml
name: "MetaMask Security Action"

on:
  workflow_dispatch:
    inputs:
      paths_ignored:
        description: 'Comma delimited paths to ignore during scan' 
        required: false
        default: 'data'
      rules_excluded:
        description: 'Comma delimited IDs of rules to exclude' 
        required: false
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    steps:   
      - name: MetaMask Security Code Scanner
        uses: MetaMask/Security-Code-Scanner@main
        with:
          repo: ${{ github.repository }}
          paths_ignored: ${{ inputs.paths_ignored }}
          rules_excluded: ${{ inputs.rules_excluded }}
          
